### ISSUE TITLE
Error "'NoneType' object has no attribute 'split'" when reusing an existing device

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [synacktiv/SCCMSecrets#1]
Hi,

Thank you for this tool. I look forward to use it in the future.

Reusing an existing device errors with "'NoneType' object has no attribute 'split'". The device was previously added using SCCMSecrets:

![sccmsecrets1_part1](https://github.com/user-attachments/assets/56d5c999-329e-4a1e-965b-f16c3febb15c)

![sccmsecrets1_part2](https://github.com/user-attachments/assets/f53d6cd1-5efe-4734-9cec-5e9b503fc82a)

**Comment by q-roland** [comment]
Hi,

The error reported in this issue seems to be triggered by the fact that you did not provide a `--client-name` argument to the command. For reusing a device, this should correspond to the client name you specified when registering the client the first time.

I will keep the issue open for now, in order to add an additional argument coherence check to verify that the user provides a client name when reusing an existing device. In addition, I may simply write the client name in a file under the `device/` output directory, so that it is automatically reused by SCCMSecrets with the `--use-existing-device` option.

Thanks for reporting this :)

**Comment by dkjajhqu2h3j** [comment]
Adding the parameter `--client-name` this works. I assumed having the GUID of the device would be enough. Clearly not. Thanks! 

I think writing the client name in `device/` is a good idea.

**Comment by q-roland** [comment]
Hi,

Commit 32600e2 adds an argument coherence check to ensure users provide a client name when reusing a device.
Commit 445b829 allows writing the provided client name to the 'device/client_name.txt' file in the loot directory.

This should provide the enhancements mentioned in this issue. Feel free to reopen it if needed.

Thanks again
