### ISSUE TITLE
Error "Unexpected mimetype in content-type: 'text/html'" when attempting to add a device authenticating using computer account credentials

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [synacktiv/SCCMSecrets#2]
Hi again,

I can add a device authenticating using user account credentials. However, when trying the same exact command using computer account credentials I get the error "Unexpected mimetype in content-type: 'text/html'":

![sccmsecrets2_lsassy](https://github.com/user-attachments/assets/dbcce3a9-7e91-468f-a628-eb463bbc1c5c)

![sccmsecrets2_part1](https://github.com/user-attachments/assets/102e2b99-f8f2-4c3c-a191-563f16be1688)

![sccmsecrets2_part2](https://github.com/user-attachments/assets/97ef74b5-bcf0-438c-b8cc-4250aacecf9a)

![sccmsecrets2_part3](https://github.com/user-attachments/assets/984656c1-a625-4806-af91-5e5971c520c2)

I also have a request for you. In my experience it is much more common to have access to the NTLM hash of computer accounts rather than their plaintext password. Will you support NTLM authentication for both computer and user accounts in the future?

**Comment by q-roland** [comment]
Hi,

You seem to have provided the machine account password in an hex-encoded format, which explains the error you encounter here (the credentials are not valid, which explains why the registration attempt using the authenticated endpoint fails and raises an exception).

I will keep this issue open for now, since it would indeed be useful to allow users to provide NT hashes of user/computer accounts (in the meantime, you can perform your tests by creating a machine account with a known plaintext password for instance).

I'Il try to work on the NT hash feature soon, I'Il keep you posted. Thanks !

**Comment by dkjajhqu2h3j** [comment]
This works using correct plaintext credentials. However, I also noted that all incorrect credentials, password and/or sAMAccountName, regardless of type, triggers this error. I know which error to look for now but perhaps this exception should be caught by the tool and a friendly information message should be printed instead?

I very much look forward to the NTLM auth support since resetting the password of live computer accounts isn't something I would do . Thanks!

**Comment by q-roland** [comment]
Hi,

Commit 32600e2 adds the possibility to login with the NT Hash of the provided users / machine accounts. It also provides better exception handling for more friendly error messages :)

Thanks again, I'm closing the issue but feel free to reopen it if needed. Cheers!
